- job:
    name: opendev-website-build
    description: |
      Publishes a draft version of the OpenDev website.
    success-url: www/
    run: playbooks/copy-to-logs.yaml
    nodeset:
      nodes: []

- job:
    name: opendev-website-publish
    parent: publish-opendev-website
    description: |
      Publishes the OpenDev website.
    run: playbooks/copy-to-artifacts.yaml
    nodeset:
      nodes: []

- project:
    check:
      jobs:
        - opendev-website-build
    gate:
      jobs:
        - opendev-website-build
    post:
      jobs:
        - opendev-website-publish
