- job:
    name: opendev-website-build
    description: |
      Publishes a draft version of the OpenDev website.
    success-url: www/
    run: playbooks/copy-to-logs.yaml
    nodeset:
      nodes: []

- project:
    check:
      jobs:
        - opendev-website-build
    gate:
      jobs:
        - opendev-website-build
